# This file was generated by GoReleaser. DO NOT EDIT.
cask "cull" do
  name "cull"
  desc "Interactive disk space analyzer for macOS and Linux"
  homepage "https://github.com/legostin/cull"
  version "0.6.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cull"

  on_macos do
    on_intel do
      url "https://github.com/legostin/cull/releases/download/v#{version}/cull_darwin_amd64.tar.gz"
      sha256 "9114aa601d7db734b212ad886818daff663021fe5fc6f67e976f40f70394b644"
    end
    on_arm do
      url "https://github.com/legostin/cull/releases/download/v#{version}/cull_darwin_arm64.tar.gz"
      sha256 "3764731ff21a0168576cc340669ce985dc4e4e3f3a2dd475bad8155c64d095e3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/legostin/cull/releases/download/v#{version}/cull_linux_amd64.tar.gz"
      sha256 "7303142728a99827e40c53350a259d87e586b44c00fea7f42e79cffea08d8237"
    end
    on_arm do
      url "https://github.com/legostin/cull/releases/download/v#{version}/cull_linux_arm64.tar.gz"
      sha256 "4d3ade848b67487e5f6ebda2d736bd6d182d9bfdb49b279d6920ff5c79f95f6b"
    end
  end

  # No zap stanza required
end
