# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cull < Formula
  desc "Interactive disk space analyzer for macOS and Linux"
  homepage "https://github.com/legostin/cull"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_darwin_amd64.tar.gz"
      sha256 "3365e1e3e6b1d1f44fbd9221ace6b9850c6670f1de8cb13cede9831bc1e7ddb2"

      define_method(:install) do
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_darwin_arm64.tar.gz"
      sha256 "71e332d4e82584651a5e0bbfafaa9c52832532389b016ec32b7ca2f8017056a9"

      define_method(:install) do
        bin.install "cull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_linux_amd64.tar.gz"
      sha256 "aec7a43da71d0013fbdaa5fc1bf1e1ca8cfd05477c3bdcd38bbdbd97e8b4dee9"
      define_method(:install) do
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_linux_arm64.tar.gz"
      sha256 "9d7b61132e0545f79c16ea21f5b088d62ee28910966aff42e328e1d0ee0c9520"
      define_method(:install) do
        bin.install "cull"
      end
    end
  end
end
