# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cull < Formula
  desc "Interactive disk space analyzer for macOS and Linux"
  homepage "https://github.com/legostin/cull"
  version "0.8.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_darwin_amd64.tar.gz"
      sha256 "9436841b7ecdffd2d6a0c54ef1c3f4ab9a624fd99dcbf8e9dc0535fddb2fea8f"

      def install
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_darwin_arm64.tar.gz"
      sha256 "4bfe220deafdd608c64ed314fbd7fb81b38092221b4624ab0fc9fee7025029fb"

      def install
        bin.install "cull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_linux_amd64.tar.gz"
      sha256 "99d071298562831222db0a43f82cd36bde78a91845cca727322d859e4ff655ec"
      def install
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.8.0/cull_linux_arm64.tar.gz"
      sha256 "08436ef16806a8916c249b424e6d9faaa78cf7d84a28b4a8e739725bc2488a05"
      def install
        bin.install "cull"
      end
    end
  end
end
