# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cull < Formula
  desc "Interactive disk space analyzer for macOS and Linux"
  homepage "https://github.com/legostin/cull"
  version "0.6.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legostin/cull/releases/download/v0.6.1/cull_darwin_amd64.tar.gz"
      sha256 "53552cbef9b6ee568badcd87b2baf8fc118cd22adc533ebfef980b4222fe29c4"

      def install
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legostin/cull/releases/download/v0.6.1/cull_darwin_arm64.tar.gz"
      sha256 "52df871229029a24b27ce14f4a3577c73410ba518bb4e1c295ceb3bd42aa9823"

      def install
        bin.install "cull"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.6.1/cull_linux_amd64.tar.gz"
      sha256 "d76dee9900e85667e5696c656054a50336aea3dc5160baed4916c7a3141efb47"
      def install
        bin.install "cull"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/cull/releases/download/v0.6.1/cull_linux_arm64.tar.gz"
      sha256 "af880f12dc92eea6d7ed29a2640969a19f52b1d098b9557cf60e23b39fefa74c"
      def install
        bin.install "cull"
      end
    end
  end
end
