# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reap < Formula
  desc "Interactive TUI for viewing and killing processes on ports. Like htop meets lsof."
  homepage "https://github.com/legostin/reap"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/legostin/reap/releases/download/v0.1.0/reap_darwin_amd64.tar.gz"
      sha256 "122c34c407e7f1610ab38a5add7f1db83ac82359e5f6f8f6ee1ce4a464a4ab29"

      def install
        bin.install "reap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/legostin/reap/releases/download/v0.1.0/reap_darwin_arm64.tar.gz"
      sha256 "8efd63305fde4c7675d3d6d8432f3d6fb9c3e8bacdbd4f2865cb83a6e3d92586"

      def install
        bin.install "reap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/reap/releases/download/v0.1.0/reap_linux_amd64.tar.gz"
      sha256 "f519fac622c1c2efeb64afab2263b22b60e4be92e659f8b1737769c1af440952"
      def install
        bin.install "reap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/legostin/reap/releases/download/v0.1.0/reap_linux_arm64.tar.gz"
      sha256 "ad1223f63d8f7a86b9dfaa937aafab525b036dee978f3cf5f042e5c45f2bc2c6"
      def install
        bin.install "reap"
      end
    end
  end
end
